### ISSUE TITLE
No response from bot

### ISSUE THREAD

**Issue by Busy-GamerRS** [radiantly/live-countdown-bot#13]
No matter what command I enter, I'm no longer getting a response from the bot. It was working just the other day but now nothing. I can't even setup a new timer. Discord says the bot is online... Does the issue have something to do with the "Docker build Failing" on the invite page for the bot?

**Comment by radiantly** [comment]
Docker is no longer used, which is why the page says it fails and is not relevant to the actual status of the bot. Could you please join the support server and report your problem? (Find the link on either the top.gg page or using the `!help` command).

I suspect that the issue might be that 
 - permissions are incorrect, or
 - someone has changed the bot prefix - tag the bot to find the new prefix

Testing the bot, I do not see a problem, so closing this issue for now.
